const questions = [
  // 5.1 Oils and Fats
  {section:'5.1',topic:'Definition',q:'Which statement best describes oils and fats?',options:['They are alcohols formed from glycerol only.','They are esters formed from fatty acids and glycerol.','They are salts formed from fatty acids and alkalis.','They are carboxylic acids formed from hydrocarbons.'],answer:1,exp:'油和脂肪本質上是酯（esters），由脂肪酸與 glycerol（propan-1,2,3-triol）形成。'},
  {section:'5.1',topic:'Physical state',q:'At room temperature, which combination is generally correct?',options:['Oils are liquid and fats are solid.','Both oils and fats are always solid.','Oils are solid and fats are liquid.','Both oils and fats are always gases.'],answer:0,exp:'一般在室溫下，油（oils）呈液態，而脂肪（fats）呈固態，主要與脂肪酸的飽和程度及熔點有關。'},
  {section:'5.1',topic:'Sources',q:'Which pair correctly matches the usual source of an oil or fat?',options:['Palm oil — animal; butter — plant','Soybean oil — animal; butter — plant','Palm oil — plant; butter — animal','Coconut oil — animal; lard — plant'],answer:2,exp:'植物通常是油的主要來源，例如 palm oil、soybean oil、coconut oil；butter 等脂肪則常來自動物。'},
  {section:'5.1',topic:'Saturated vs unsaturated',q:'What is the key structural feature of an unsaturated fatty acid?',options:['It contains no carbon atoms.','It contains only C–C single bonds.','It contains an ionic bond between carbon atoms.','It contains at least one C=C double bond.'],answer:3,exp:'不飽和脂肪酸的碳鏈中至少含有一個 C=C 雙鍵；飽和脂肪酸的碳鏈只有 C–C 單鍵。'},
  {section:'5.1',topic:'Melting point',q:'Why do oils usually have lower melting points than fats?',options:['Oils contain only glycerol and no fatty acids.','Oils contain a higher percentage of unsaturated fatty acids.','Fats contain more water molecules.','Oils contain more ionic compounds.'],answer:1,exp:'油通常含較高比例的不飽和脂肪酸。C=C 使碳鏈較難緊密排列，因此分子間作用較弱，熔點通常較低。'},
  {section:'5.1',topic:'Hydrogenation',q:'Which conditions are used to convert unsaturated fats into more saturated fats?',options:['Nitrogen gas and copper catalyst','Oxygen gas and iron catalyst','Hydrogen gas and nickel catalyst with heating','Carbon dioxide and sodium hydroxide'],answer:2,exp:'這個反應叫 hydrogenation。把 H₂ 通入加熱的油中並使用 nickel 作催化劑，使 C=C 轉成 C–C。'},
  {section:'5.1',topic:'Hydrogenation',q:'During hydrogenation, what happens to the carbon-carbon double bonds in an unsaturated fat?',options:['They become carbon-carbon single bonds.','They become carbon-oxygen double bonds.','They are converted into ionic bonds.','They remain unchanged.'],answer:0,exp:'氫化反應會在 C=C 上加入氫，使它轉為 C–C 單鍵，所以不飽和程度下降。'},
  {section:'5.1',topic:'Application',q:'Margarine is solid at room temperature although it can be made from vegetable oil. Which process best explains this?',options:['Saponification','Neutralisation','Fermentation','Hydrogenation'],answer:3,exp:'植物油經 hydrogenation 後，不飽和程度降低、熔點上升，因此可形成室溫下較固態的 margarine。'},
  {section:'5.1',topic:'Esterification',q:'One molecule of glycerol reacts completely with three fatty acid molecules. What is formed?',options:['Three fat molecules and one water molecule','One fat molecule and three water molecules','One soap molecule and three hydrogen molecules','Three alcohol molecules and one ester molecule'],answer:1,exp:'一個 glycerol 有三個 –OH，可和三個 fatty acid 酯化，形成一個 triglyceride 以及 3H₂O。'},
  {section:'5.1',topic:'Fatty acids',q:'Which of the following is an example of an unsaturated fatty acid?',options:['Stearic acid','Palmitic acid','Lauric acid','Linoleic acid'],answer:3,exp:'Linoleic acid 是不飽和脂肪酸；stearic acid、palmitic acid、lauric acid 則是常見飽和脂肪酸例子。'},
  {section:'5.1',topic:'Nutrition',q:'Oils and fats help the body absorb which group of vitamins?',options:['Vitamins B and C only','Vitamins A, D, E and K','Vitamin C only','All vitamins equally without exception'],answer:1,exp:'A、D、E、K 是脂溶性維生素，因此適量 oils and fats 能幫助人體吸收這些維生素。'},
  {section:'5.1',topic:'Daily uses',q:'Which is NOT a common use of oils and fats discussed in this topic?',options:['Producing biodiesel','Making soap and personal-care products','Producing chlorine gas for water treatment','Manufacturing animal feed'],answer:2,exp:'油脂可用於 biofuel、營養、製皂與個人護理產品、animal feed 等；製造 chlorine gas 並不是此處用途。'},
  {section:'5.1',topic:'Health',q:'Excessive intake of saturated fats is associated with a higher risk of which condition?',options:['Arteriosclerosis','Scurvy','Dehydration','Night blindness caused by vitamin A deficiency'],answer:0,exp:'過量攝取飽和脂肪會增加心血管相關風險，課本常以 arteriosclerosis（動脈硬化）作例子。'},
  {section:'5.1',topic:'Comparison',q:'A sample is liquid at room temperature and contains a high percentage of unsaturated fatty acids. It is most likely a(n) _____.',options:['fat','soap','detergent','oil'],answer:3,exp:'液態 + 高比例不飽和脂肪酸是 oils 的典型特徵；fats 通常在室溫下較固態。'},
  {section:'5.1',topic:'Reasoning',q:'Which change would most likely increase the melting point of a vegetable oil?',options:['Increasing the number of C=C bonds','Adding more water only','Hydrogenating some of its C=C bonds','Converting it into a carboxylic acid salt'],answer:2,exp:'hydrogenation 減少 C=C、提高飽和程度，使分子更容易排列緊密，因此通常會提高熔點。'},

  // 5.2 Cleaning Agents
  {section:'5.2',topic:'Soap',q:'What is soap?',options:['A pure hydrocarbon obtained from petroleum','A sodium or potassium salt of a fatty acid','An ester of glycerol and sulphuric acid','A sodium salt of nitric acid'],answer:1,exp:'Soap 是脂肪酸的 sodium salt 或 potassium salt，常見形式可寫成 RCOO⁻Na⁺ 或 RCOO⁻K⁺。'},
  {section:'5.2',topic:'Soap formula',q:'Which formula best represents a sodium soap?',options:['RCOOH','ROH','RCOONa','RCl'],answer:2,exp:'sodium soap 的一般形式是 RCOO⁻Na⁺，簡寫為 RCOONa；R 是長碳鏈烷基。'},
  {section:'5.2',topic:'Detergent',q:'Which statement about detergents is correct?',options:['They are always potassium salts of fatty acids.','They cannot work in water.','They are triglycerides obtained only from animal fats.','They are non-soap cleaning agents commonly made from petroleum-based raw materials.'],answer:3,exp:'Detergents 是非皂類清潔劑，通常由 petroleum-based raw materials 合成；其親水端結構與 soap 不同。'},
  {section:'5.2',topic:'Saponification',q:'What is the name of the alkaline hydrolysis of oils or fats to produce soap?',options:['Saponification','Hydrogenation','Polymerisation','Oxidation'],answer:0,exp:'油或脂肪被濃鹼水解，生成 glycerol 和 fatty acid salts（soap），這個過程叫 saponification。'},
  {section:'5.2',topic:'Saponification products',q:'Which products are formed when an oil or fat reacts with concentrated NaOH during saponification?',options:['Detergent and hydrogen','Alcohol and carbon dioxide','Fatty acid and oxygen','Soap and glycerol'],answer:3,exp:'Oil/Fat + concentrated alkali → Soap + Glycerol。使用 NaOH 會生成 sodium salts of fatty acids。'},
  {section:'5.2',topic:'Detergent preparation',q:'Which pair of processes is used in the preparation of many detergents?',options:['Hydrogenation followed by esterification','Sulphonation or sulphation followed by neutralisation','Combustion followed by electrolysis','Fermentation followed by distillation'],answer:1,exp:'detergent 製備常包含 sulphonation 或 sulphation，之後 neutralisation 生成相應的 sodium salt。'},
  {section:'5.2',topic:'Molecular structure',q:'In a soap or detergent anion, which part is soluble in water?',options:['The entire molecule is insoluble in water','Only the carbon-carbon bonds','The hydrophilic part','The hydrophobic hydrocarbon chain only'],answer:2,exp:'hydrophilic（親水）部分可與水作用；hydrophobic（疏水）長碳鏈則偏向油脂。'},
  {section:'5.2',topic:'Molecular structure',q:'During cleaning, where does the hydrophobic part of a soap or detergent anion tend to dissolve?',options:['In oil or grease','Only in pure water','In sodium ions','In the cloth fibre only'],answer:0,exp:'疏水端是長碳鏈，會進入 grease 或 oil；親水端留在水相中，幫助把油污分散到水裡。'},
  {section:'5.2',topic:'Cleansing action',q:'What is an important first effect when soap or detergent is added to water?',options:['Water becomes completely non-polar.','The surface tension of water decreases.','The surface tension of water increases greatly.','All ions in the water precipitate immediately.'],answer:1,exp:'soap/detergent 會降低水的表面張力，使水更容易潤濕布料表面，這是清潔作用的重要起點。'},
  {section:'5.2',topic:'Emulsion',q:'Why do grease droplets remain suspended in water after being surrounded by soap or detergent anions?',options:['The grease changes into sodium metal.','The cloth becomes positively charged permanently.','The grease evaporates instantly.','Like charges on the hydrophilic ends repel one another and help prevent reattachment.'],answer:3,exp:'油滴表面被帶相同電荷的親水端包圍，彼此排斥，使油滴較不容易重新聚集或黏回布料，形成 emulsion。'},
  {section:'5.2',topic:'Hard water',q:'Which ions are mainly responsible for hard water in this topic?',options:['Na⁺ and K⁺','H⁺ and OH⁻','Ca²⁺ and Mg²⁺','Cl⁻ and NO₃⁻'],answer:2,exp:'hard water 主要含較多 Ca²⁺ 與 Mg²⁺，它們會與 soap anions 形成不溶性 salts（scum）。'},
  {section:'5.2',topic:'Soap in hard water',q:'Why is soap less effective in hard water?',options:['Soap anions form insoluble scum with Ca²⁺ or Mg²⁺ ions.','Soap turns all water into oil.','NaOH is always produced and destroys the cloth.','Soap cannot ionise in any type of water.'],answer:0,exp:'soap anions 和 Ca²⁺/Mg²⁺ 形成不溶性 scum，消耗了一部分 soap，所以需要更多 soap 才能達到清潔效果。'},
  {section:'5.2',topic:'Detergent in hard water',q:'Why are detergents generally more effective than soap in hard water?',options:['They remove Ca²⁺ by producing oxygen gas.','They contain no hydrophobic part.','Their salts with Ca²⁺ and Mg²⁺ remain soluble in water.','They always make the water acidic.'],answer:2,exp:'detergent anions 與 Ca²⁺/Mg²⁺ 形成的 salts 仍可溶於水，因此不像 soap 那樣大量形成 scum。'},
  {section:'5.2',topic:'Acidic water',q:'Which comparison is correct in acidic water?',options:['Soap is more effective, while detergent forms scum immediately.','Soap is less effective, while detergent remains effective.','Both become metals.','Neither can interact with grease.'],answer:1,exp:'酸性水中 soap 會形成較難溶的 fatty acid，清潔效果下降；detergent 通常仍能保持較好的清潔效果。'},
  {section:'5.2',topic:'Application',q:'A student washes an oily cloth in water containing many Ca²⁺ ions. Which choice should give the best cleaning result?',options:['Use soap because more scum means better cleaning.','Use only vegetable oil.','Add more Ca²⁺ ions before using soap.','Use detergent because it remains effective in hard water.'],answer:3,exp:'Ca²⁺ 多表示 hard water。soap 容易形成 scum；detergent 在 hard water 中通常更有效。'}
];

const $ = id => document.getElementById(id);
const startScreen=$('startScreen'),quizScreen=$('quizScreen'),reportScreen=$('reportScreen'),quizForm=$('quizForm');
const studentNameInput=$('studentName'),startBtn=$('startBtn'),submitBtn=$('submitBtn'),copyLinkBtn=$('copyLinkBtn'),printBtn=$('printBtn'),retryBtn=$('retryBtn'),toast=$('toast');
let studentName='',lastAnswers=[];

function esc(str=''){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderQuiz(){
  quizForm.innerHTML=questions.map((item,i)=>`<article class="card question-card" data-index="${i}"><div class="q-meta"><span class="q-num">Q${i+1} · ${item.section}</span><span class="q-topic">${esc(item.topic)}</span></div><h3>${esc(item.q)}</h3><div class="options">${item.options.map((opt,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"/><span class="letter">${String.fromCharCode(65+j)}</span><span>${esc(opt)}</span></label>`).join('')}</div></article>`).join('');
  quizForm.addEventListener('change',updateProgress);
}
function updateProgress(){let answered=0;questions.forEach((_,i)=>{if(quizForm.querySelector(`input[name="q${i}"]:checked`))answered++;});$('answeredCount').textContent=`${answered} answered`;$('progressBar').style.width=`${answered/questions.length*100}%`;$('progressText').textContent=`${answered} of ${questions.length} completed`;$('sectionLabel').textContent=answered<15?'Section 5.1':'Section 5.2';}
function getAnswers(){return questions.map((_,i)=>{const selected=quizForm.querySelector(`input[name="q${i}"]:checked`);return selected?Number(selected.value):-1;});}
function compute(answers){const correct=answers.map((a,i)=>a===questions[i].answer),score=correct.filter(Boolean).length,score51=correct.slice(0,15).filter(Boolean).length,score52=correct.slice(15).filter(Boolean).length;return{correct,score,score51,score52,pct:Math.round(score/30*100)};}
function answerText(q,idx){return idx===-1||idx===undefined||idx===null?'No answer':`${String.fromCharCode(65+idx)}. ${q.options[idx]}`;}
function renderReviewItem(q,i,chosen,isCorrect,includeCorrectItems=true){if(!includeCorrectItems&&isCorrect)return'';return`<article class="review-item ${isCorrect?'correct':'wrong'}"><div class="review-top"><div class="review-q"><span class="q-num">Q${i+1} · ${q.section}</span><br>${esc(q.q)}</div><span class="status ${isCorrect?'good':'bad'}">${isCorrect?'✓ Correct':'✕ Review'}</span></div><div class="answer-lines"><div class="your"><strong>Your answer:</strong> ${esc(answerText(q,chosen))}</div><div class="correct-answer"><strong>Correct answer:</strong> ${esc(answerText(q,q.answer))}</div><div class="explanation"><strong>中文解析：</strong>${esc(q.exp)}</div></div></article>`;}
function showReport(name,answers,shared=false){
  studentName=name||'Student';lastAnswers=answers;const r=compute(answers),wrong=30-r.score;
  startScreen.classList.add('hidden');quizScreen.classList.add('hidden');reportScreen.classList.remove('hidden');
  $('reportTitle').textContent=`${studentName}'s Results`;$('reportMeta').textContent=shared?'Shared revision report · Form 5 Chemistry 5.1 & 5.2':`Completed ${new Date().toLocaleString()}`;$('scorePct').textContent=`${r.pct}%`;$('overallScore').textContent=`${r.score} / 30`;$('score51').textContent=`${r.score51} / 15`;$('score52').textContent=`${r.score52} / 15`;$('wrongCount').textContent=String(wrong);$('reviewBadge').textContent=wrong===0?'All correct':`${wrong} to discuss`;$('scoreRing').style.background=`conic-gradient(var(--accent) ${r.pct*3.6}deg, #162c43 0deg)`;
  const wrongHtml=questions.map((q,i)=>renderReviewItem(q,i,answers[i],r.correct[i],false)).join('');$('wrongReview').innerHTML=wrongHtml?`<div class="review-list">${wrongHtml}</div>`:'<div class="empty-review">Excellent — no wrong answers. You are ready to move on.</div>';$('fullReview').innerHTML=`<div class="review-list">${questions.map((q,i)=>renderReviewItem(q,i,answers[i],r.correct[i],true)).join('')}</div>`;
  if(shared)copyLinkBtn.textContent='Copy This Report Link';window.scrollTo({top:0,behavior:'smooth'});
}
function encodeReport(name,answers){const payload=JSON.stringify({n:name,a:answers}),bytes=new TextEncoder().encode(payload);let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decodeReport(encoded){const b64=encoded.replace(/-/g,'+').replace(/_/g,'/'),padded=b64+'='.repeat((4-b64.length%4)%4),binary=atob(padded),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}
function buildShareUrl(){return`${location.origin}${location.pathname}#report=${encodeReport(studentName,lastAnswers)}`;}
function showToast(msg){toast.textContent=msg;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),2200);}

startBtn.addEventListener('click',()=>{studentName=studentNameInput.value.trim()||'Student';startScreen.classList.add('hidden');quizScreen.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});});
submitBtn.addEventListener('click',()=>{const answers=getAnswers(),unanswered=answers.filter(a=>a===-1).length;if(unanswered>0&&!confirm(`${unanswered} question(s) are unanswered. Submit anyway?`))return;showReport(studentName,answers,false);history.replaceState(null,'',location.pathname);});
copyLinkBtn.addEventListener('click',async()=>{const url=buildShareUrl();try{await navigator.clipboard.writeText(url);showToast('Report link copied');}catch{prompt('Copy this report link:',url);}});
printBtn.addEventListener('click',()=>window.print());
retryBtn.addEventListener('click',()=>{history.replaceState(null,'',location.pathname);reportScreen.classList.add('hidden');startScreen.classList.remove('hidden');quizForm.reset();updateProgress();window.scrollTo({top:0,behavior:'smooth'});});
function loadSharedReport(){const match=location.hash.match(/^#report=(.+)$/);if(!match)return false;try{const data=decodeReport(match[1]);if(!Array.isArray(data.a)||data.a.length!==questions.length)throw new Error('Invalid report');showReport(String(data.n||'Student'),data.a.map(Number),true);return true;}catch(err){console.error(err);showToast('This report link is invalid or incomplete.');return false;}}

renderQuiz();if(!loadSharedReport())updateProgress();
