const questions = [
  // 5.3 Food Additives
  {section:'5.3',topic:'Definition',q:'Which statement best describes a food additive?',options:['A nutrient naturally present in every food','A substance added to food to prevent damage or improve appearance, taste or texture','A microorganism that always spoils food','A chemical used only to increase the mass of food'],answer:1,exp:'Food additive 是加入食物中的天然或合成成分，目的可以是延缓食物变坏，或改善外观、味道和质地。'},
  {section:'5.3',topic:'Types',q:'Which of the following is NOT one of the seven main types of food additives in this topic?',options:['Preservatives','Antioxidants','Catalysts','Emulsifiers'],answer:2,exp:'课本列出的七类是 preservatives、antioxidants、flavourings、stabilisers、emulsifiers、thickeners 和 dyes；catalysts 不属于这七类。'},
  {section:'5.3',topic:'Preservatives',q:'What is the main function of preservatives in food?',options:['To speed up oxidation of fats','To prevent or delay the growth of bacteria or fungi','To make two immiscible liquids separate faster','To remove all colour from food'],answer:1,exp:'Preservatives 主要通过抑制或延缓细菌、真菌生长，使食物保存更久。'},
  {section:'5.3',topic:'Preservatives',q:'Which pair correctly matches a preservative with its food use?',options:['Sodium benzoate — bread','Lecithin — dried fish','Xanthan gum — sausages','Tocopherol — pickles'],answer:0,exp:'课本例子包括 sodium benzoate in bread；其他常见防腐剂还有 salt、sugar、vinegar、benzoic acid、sodium nitrite/nitrate 和 sulphur dioxide。'},
  {section:'5.3',topic:'Antioxidants',q:'Why are antioxidants added to oily or fatty foods?',options:['To increase bacterial growth','To speed up rancidity','To slow down oxidation and prevent rancidity','To convert oils into proteins'],answer:2,exp:'Antioxidants 会减慢脂肪被氧化的速度，从而避免油脂产生 rancid（酸败）气味和味道。'},
  {section:'5.3',topic:'Antioxidants',q:'Which substance is used as an antioxidant in margarine?',options:['Tocopherol (Vitamin E)','Sodium chloride','Lecithin','Azo dye'],answer:0,exp:'Tocopherol（Vitamin E）是课本列出的 antioxidant 例子，可用于 margarine。'},
  {section:'5.3',topic:'Flavourings',q:'Which food additive is commonly used as a flavour enhancer in instant noodles?',options:['Monosodium glutamate (MSG)','Formaldehyde','Sodium hydroxide','Hydrogen peroxide'],answer:0,exp:'MSG（monosodium glutamate）属于 flavouring / flavour enhancer，可增强食物的鲜味。'},
  {section:'5.3',topic:'Flavourings',q:'Which ester is associated with pineapple flavour in the textbook?',options:['Propyl ethanoate','Ethyl ethanoate','Methyl methanoate','Ethyl chloride'],answer:1,exp:'课本例子：ethyl ethanoate 可提供 pineapple flavour；propyl ethanoate 则与 pear flavour 相关。'},
  {section:'5.3',topic:'Stabilisers',q:'What is the main purpose of stabilisers in food?',options:['To give food a uniform and smooth texture','To destroy all vitamins','To make food strongly acidic','To produce carbon dioxide gas'],answer:0,exp:'Stabilisers 的作用是帮助食物保持均匀、顺滑的质地，使成分在储存时更稳定。'},
  {section:'5.3',topic:'Emulsifiers',q:'What does an emulsifier do?',options:['It separates oil and water completely','It helps two immiscible liquids form an emulsion','It increases the melting point of metals','It changes sugar into salt'],answer:1,exp:'Emulsifier 能帮助原本不互溶的两种液体（例如 oil 和 water）形成较均匀的混合体系。'},
  {section:'5.3',topic:'Emulsifiers',q:'Which is an example of an emulsifier used in food?',options:['Lecithin in chocolate','Sulphur dioxide in dried fruit','Sodium nitrite in sausage','Caramel as a brown colouring'],answer:0,exp:'Lecithin 是课本列出的 emulsifier 例子，可用于 chocolate；它帮助不同相的成分均匀混合。'},
  {section:'5.3',topic:'Thickeners',q:'Which additive is used mainly to increase the viscosity of soups and sauces?',options:['A thickener such as xanthan gum','A preservative such as sodium nitrite','An antioxidant such as tocopherol','A dye such as an azo compound'],answer:0,exp:'Thickeners 用来增加液体黏度。课本例子包括 starch、gelatine、acacia gum 和 xanthan gum。'},
  {section:'5.3',topic:'Dyes',q:'What is the purpose of food dyes?',options:['To add or restore colour and improve appearance','To kill bacteria by heating','To reduce the amount of water in food','To convert fat into glycerol'],answer:0,exp:'Dyes 的作用是加入或恢复颜色，使食物看起来更吸引人；例如 caramel 可提供 brown colour。'},
  {section:'5.3',topic:'Ingredient label',q:'A margarine label lists ascorbic acid as an ingredient. What type of food additive is it?',options:['Preservative','Antioxidant','Emulsifier','Thickener'],answer:1,exp:'Ascorbic acid（Vitamin C）在这个课题中属于 antioxidant，用来减慢氧化过程。'},
  {section:'5.3',topic:'Justification',q:'Which statement best justifies the use of food additives?',options:['They should be used without any limit because all additives are harmless.','They can improve shelf life, taste or appearance when used within regulated amounts.','They are required to replace all natural ingredients.','They guarantee that processed food is always healthier than fresh food.'],answer:1,exp:'Food additives 有实际用途，例如延长保存时间、改善味道和外观，但必须遵守规定用量。过量摄取某些添加剂可能带来健康问题。'},

  // 5.4 Medicines and Cosmetics
  {section:'5.4',topic:'Traditional medicines',q:'Which statement best describes traditional medicines?',options:['They are always made entirely from synthetic chemicals.','They are commonly obtained from plants or animals and traditionally are not chemically processed.','They can only exist as injections.','They have no biological source.'],answer:1,exp:'Traditional medicines 通常来自植物或动物，传统制备方式多是捣碎、煮取精华等，并非以化学加工为主。'},
  {section:'5.4',topic:'Traditional medicines',q:'Which traditional medicine is associated with preventing colds and warming the body?',options:['Ginger','Aloe vera','Tamarind','Penicillin'],answer:0,exp:'课本列出 ginger 的用途包括帮助排风、预防感冒以及使身体温暖。'},
  {section:'5.4',topic:'Analgesics',q:'Which type of modern medicine is used mainly to relieve pain while the patient remains conscious?',options:['Analgesic','Disinfectant','Food preservative','Emulsifier'],answer:0,exp:'Analgesics 是止痛药，例如 aspirin、paracetamol 和 codeine；其中 aspirin 和 paracetamol 可在保持清醒的情况下缓解疼痛。'},
  {section:'5.4',topic:'Analgesics',q:'What can happen if paracetamol is taken in excessive amounts?',options:['Liver damage','Stronger bones','Permanent immunity to bacteria','Increased skin pigmentation'],answer:0,exp:'Paracetamol overdose 可造成 liver damage，因此必须按正确剂量使用。'},
  {section:'5.4',topic:'Analgesics',q:'Why is aspirin generally unsuitable for gastric patients or children in this syllabus?',options:['It is strongly alkaline and causes dehydration.','It is acidic and may cause stomach ulcers.','It always causes kidney stones immediately.','It destroys all red blood cells.'],answer:1,exp:'课本指出 aspirin 具有酸性，可能造成 stomach ulcers，因此不适合 gastric patients 或 children。'},
  {section:'5.4',topic:'Antimicrobials',q:'Which statement correctly distinguishes antiseptics from disinfectants?',options:['Antiseptics are used on skin, while disinfectants are used on non-living surfaces.','Antiseptics are only swallowed, while disinfectants are injected.','Both are used only as food additives.','Disinfectants are always applied to open wounds.'],answer:0,exp:'Antiseptics 用于皮肤等活体表面；disinfectants 用于地面、排水系统等非生命物体表面。'},
  {section:'5.4',topic:'Antibiotics',q:'Why should a prescribed course of antibiotics be completed?',options:['To make the medicine taste better','To ensure bacteria are eliminated and reduce the risk of antibiotic resistance','To convert antibiotics into analgesics','To prevent the medicine from dissolving'],answer:1,exp:'抗生素应按疗程完整服用，否则未被消灭的细菌可能存活并产生 resistance，疾病也可能复发。'},
  {section:'5.4',topic:'Psychotic drugs',q:'Which medicine is an example of a psychotic drug used in the treatment of psychosis?',options:['Haloperidol','Ascorbic acid','Sodium benzoate','Lecithin'],answer:0,exp:'Haloperidol、chlorpromazine 和 clozapine 是课本中的 psychotic drugs 例子，用于治疗 psychosis。'},
  {section:'5.4',topic:'Anti-allergies',q:'What is a common use of antihistamines?',options:['To relieve runny nose and itchiness','To thicken cosmetic creams','To kill bacteria on floors','To preserve dried fruits'],answer:0,exp:'Antihistamines 属于 anti-allergy medicines，可缓解流鼻水和痕痒；副作用可能包括 drowsiness。'},
  {section:'5.4',topic:'Corticosteroids',q:'Which is a function of corticosteroids such as prednisolone?',options:['To increase inflammation','To reduce swelling, redness and allergic reactions','To act as a food colouring','To produce fragrance in cosmetics'],answer:1,exp:'Corticosteroids 可减轻发炎、肿胀、发红、痕痒、过敏反应，也可用于 asthma 和 arthritis 等情况，但应按医生处方使用。'},
  {section:'5.4',topic:'Medicine safety',q:'Which is the safest principle when using medicines?',options:['Increase the dose whenever symptoms feel severe.','Share prescription medicines with friends who have similar symptoms.','Follow the correct dosage and medical instructions.','Stop antibiotics immediately after feeling better.'],answer:2,exp:'无论 modern 或 traditional medicines，都应重视正确剂量与专业指示。错误剂量和滥用可能造成副作用、耐药性、成瘾或器官损害。'},
  {section:'5.4',topic:'Cosmetics',q:'Which statement best defines cosmetics?',options:['Products used externally to cleanse, protect or enhance appearance','Chemicals used only to cure bacterial infections','Substances added only to preserve food','Materials used only in industrial metal extraction'],answer:0,exp:'Cosmetics 是外用材料或产品，用来清洁、保护或改善个人外观。'},
  {section:'5.4',topic:'Cosmetic ingredients',q:'What is the function of an emulsifier in a cosmetic product?',options:['To form a homogeneous mixture between oil and water','To destroy the product colour','To make bacteria grow faster','To remove all moisture from the product'],answer:0,exp:'Cosmetic emulsifier 帮助 oil 和 water 形成均匀混合物；课本例子包括 lecithin 和 stearic acid。'},
  {section:'5.4',topic:'Types of cosmetics',q:'Which set contains the three main groups of cosmetics in this topic?',options:['Makeup cosmetics, treatment cosmetics and fragrances','Analgesics, antibiotics and antiseptics','Preservatives, antioxidants and dyes','Soaps, detergents and fertilisers'],answer:0,exp:'课本把 cosmetics 分成三大类：makeup cosmetics、treatment cosmetics 和 fragrances。'},
  {section:'5.4',topic:'Cosmetic safety',q:'A whitening cream contains illegally added mercury. Which risk is associated with mercury exposure?',options:['Skin irritation and possible kidney or nervous system damage','Improved antibiotic effectiveness','Higher vitamin C absorption','Faster wound healing with no side effects'],answer:0,exp:'Mercury 可能造成皮肤刺激；如果被吸收到血液，也可能伤害 kidney 和 nervous system。因此应检查产品安全与注册状态。'}
];

const $ = id => document.getElementById(id);
const startScreen=$('startScreen'),quizScreen=$('quizScreen'),reportScreen=$('reportScreen'),quizForm=$('quizForm');
const studentNameInput=$('studentName'),startBtn=$('startBtn'),submitBtn=$('submitBtn'),copyLinkBtn=$('copyLinkBtn'),printBtn=$('printBtn'),retryBtn=$('retryBtn'),toast=$('toast');
let studentName='',lastAnswers=[];

function esc(str=''){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderQuiz(){
  quizForm.innerHTML=questions.map((item,i)=>`<article class="card question-card" data-index="${i}"><div class="q-meta"><span class="q-num">Q${i+1} · ${item.section}</span><span class="q-topic">${esc(item.topic)}</span></div><h3>${esc(item.q)}</h3><div class="options">${item.options.map((opt,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"/><span class="letter">${String.fromCharCode(65+j)}</span><span>${esc(opt)}</span></label>`).join('')}</div></article>`).join('');
  quizForm.addEventListener('change',updateProgress);
}
function updateProgress(){let answered=0;questions.forEach((_,i)=>{if(quizForm.querySelector(`input[name="q${i}"]:checked`))answered++;});$('answeredCount').textContent=`${answered} answered`;$('progressBar').style.width=`${answered/questions.length*100}%`;$('progressText').textContent=`${answered} of ${questions.length} completed`;$('sectionLabel').textContent=answered<15?'Section 5.3':'Section 5.4';}
function getAnswers(){return questions.map((_,i)=>{const selected=quizForm.querySelector(`input[name="q${i}"]:checked`);return selected?Number(selected.value):-1;});}
function compute(answers){const correct=answers.map((a,i)=>a===questions[i].answer),score=correct.filter(Boolean).length,score53=correct.slice(0,15).filter(Boolean).length,score54=correct.slice(15).filter(Boolean).length;return{correct,score,score53,score54,pct:Math.round(score/30*100)};}
function answerText(q,idx){return idx===-1||idx===undefined||idx===null?'No answer':`${String.fromCharCode(65+idx)}. ${q.options[idx]}`;}
function renderReviewItem(q,i,chosen,isCorrect,includeCorrectItems=true){if(!includeCorrectItems&&isCorrect)return'';return`<article class="review-item ${isCorrect?'correct':'wrong'}"><div class="review-top"><div class="review-q"><span class="q-num">Q${i+1} · ${q.section}</span><br>${esc(q.q)}</div><span class="status ${isCorrect?'good':'bad'}">${isCorrect?'✓ Correct':'✕ Review'}</span></div><div class="answer-lines"><div class="your"><strong>Your answer:</strong> ${esc(answerText(q,chosen))}</div><div class="correct-answer"><strong>Correct answer:</strong> ${esc(answerText(q,q.answer))}</div><div class="explanation"><strong>中文解析：</strong>${esc(q.exp)}</div></div></article>`;}
function showReport(name,answers,shared=false){
  studentName=name||'Student';lastAnswers=answers;const r=compute(answers),wrong=30-r.score;
  startScreen.classList.add('hidden');quizScreen.classList.add('hidden');reportScreen.classList.remove('hidden');
  $('reportTitle').textContent=`${studentName}'s Results`;$('reportMeta').textContent=shared?'Shared revision report · Form 5 Chemistry 5.3 & 5.4':`Completed ${new Date().toLocaleString()}`;$('scorePct').textContent=`${r.pct}%`;$('overallScore').textContent=`${r.score} / 30`;$('score53').textContent=`${r.score53} / 15`;$('score54').textContent=`${r.score54} / 15`;$('wrongCount').textContent=String(wrong);$('reviewBadge').textContent=wrong===0?'All correct':`${wrong} to discuss`;$('scoreRing').style.background=`conic-gradient(var(--accent) ${r.pct*3.6}deg, #162c43 0deg)`;
  const wrongHtml=questions.map((q,i)=>renderReviewItem(q,i,answers[i],r.correct[i],false)).join('');$('wrongReview').innerHTML=wrongHtml?`<div class="review-list">${wrongHtml}</div>`:'<div class="empty-review">Excellent — no wrong answers. You are ready to move on.</div>';$('fullReview').innerHTML=`<div class="review-list">${questions.map((q,i)=>renderReviewItem(q,i,answers[i],r.correct[i],true)).join('')}</div>`;
  if(shared)copyLinkBtn.textContent='Copy This Report Link';window.scrollTo({top:0,behavior:'smooth'});
}
function encodeReport(name,answers){const payload=JSON.stringify({n:name,a:answers}),bytes=new TextEncoder().encode(payload);let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decodeReport(encoded){const b64=encoded.replace(/-/g,'+').replace(/_/g,'/'),padded=b64+'='.repeat((4-b64.length%4)%4),binary=atob(padded),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}
function buildShareUrl(){return`${location.origin}${location.pathname}#report=${encodeReport(studentName,lastAnswers)}`;}
function showToast(msg){toast.textContent=msg;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),2200);}

startBtn.addEventListener('click',()=>{studentName=studentNameInput.value.trim()||'Student';startScreen.classList.add('hidden');quizScreen.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});});
submitBtn.addEventListener('click',()=>{const answers=getAnswers(),unanswered=answers.filter(a=>a===-1).length;if(unanswered>0&&!confirm(`${unanswered} question(s) are unanswered. Submit anyway?`))return;showReport(studentName,answers,false);history.replaceState(null,'',location.pathname);});
copyLinkBtn.addEventListener('click',async()=>{const url=buildShareUrl();try{await navigator.clipboard.writeText(url);showToast('Report link copied');}catch{prompt('Copy this report link:',url);}});
printBtn.addEventListener('click',()=>window.print());
retryBtn.addEventListener('click',()=>{history.replaceState(null,'',location.pathname);reportScreen.classList.add('hidden');startScreen.classList.remove('hidden');quizForm.reset();updateProgress();window.scrollTo({top:0,behavior:'smooth'});});
function loadSharedReport(){const match=location.hash.match(/^#report=(.+)$/);if(!match)return false;try{const data=decodeReport(match[1]);if(!Array.isArray(data.a)||data.a.length!==questions.length)throw new Error('Invalid report');showReport(String(data.n||'Student'),data.a.map(Number),true);return true;}catch(err){console.error(err);showToast('This report link is invalid or incomplete.');return false;}}

renderQuiz();if(!loadSharedReport())updateProgress();
